# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := tess2 example

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

tess2: 
	@echo "==== Building tess2 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tess2.make

example: tess2
	@echo "==== Building example ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f example.make

clean:
	@${MAKE} --no-print-directory -C . -f tess2.make clean
	@${MAKE} --no-print-directory -C . -f example.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tess2"
	@echo "   example"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
