name: build-linux64

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
jobs:

  build-linux64:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cfg:
          - {target: linux, opt: gcc6}
    env:
     TARGET: ${{matrix.cfg.target}}
     OPT: ${{matrix.cfg.opt}}
    steps:
    - uses: actions/checkout@v4
    - name: Scripts Calc Formula - ${{matrix.cfg.target}} - ${{matrix.cfg.opt}}
      run: ./scripts/calculate_formulas.sh
    - name: Scripts Install
      run: ./scripts/$TARGET/install.sh
    - name: Determine Release
      id: vars
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "release=nightly" >> $GITHUB_ENV
          echo "prerelease=false" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
          echo "release=bleeding" >> $GITHUB_ENV
          echo "prerelease=true" >> $GITHUB_ENV
        fi
    - name: build
      run: ./scripts/build.sh
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}
    - name: Update Release 
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.release }}
        release: ${{ env.release }}
        prerelease: ${{ env.prerelease }}
        files: out/openFrameworksLibs_${{ env.release }}_linux64gcc6.tar.bz2
      if: (github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding'))
