name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-msys2:
    
    strategy:
      matrix:
        flavor:
          - mingw64
          - ucrt64
          - clang64
          #- clangarm64
    name: ${{ matrix.flavor }}
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          release : true
          msystem: ${{ matrix.flavor }}
          install: >-
            base-devel
            unzip
            dos2unix
            git
          pacboy: >-
            gcc:p
            cmake:p
            gperf:p
            libxml2:p
            python3:p
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: scripts/build.sh
        env:
          TARGET: "msys2"
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          files: out/openFrameworksLibs_msys2_${{ matrix.flavor }}.zip
        if: github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && github.ref == 'refs/heads/master'

