name: build-tvos

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

jobs:
  build-macos-platforms:
    runs-on: macos-14
    strategy:
      matrix:
        bundle: [1, 2, 3]
    env:
      TARGET: "tvos"
      BUNDLE: ${{ matrix.bundle }}
      DEVELOPER_DIR: "/Applications/Xcode_15.2.app/Contents/Developer"
    steps:
      - name: Determine Release
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "release=nightly" >> $GITHUB_ENV
            echo "prerelease=false" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
            echo "release=bleeding" >> $GITHUB_ENV
            echo "prerelease=true" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
      - name: Scripts Calc Formula - ${{ env.TARGET }} Bundle ${{ matrix.bundle }}
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/tvos/install.sh
      - name: Build tvOS arm64
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: scripts/build.sh
        env:
          TARGET: "tvos"
          BUNDLE: ${{ matrix.bundle }}
          ARCH: arm64
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Build tvOS x86_64
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: scripts/build.sh
        env:
          TARGET: "tvos"
          BUNDLE: ${{ matrix.bundle }}
          ARCH: x86_64
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Build tvOS SIMULATOR arm64
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: scripts/build.sh
        env:
          TARGET: "tvos"
          BUNDLE: ${{ matrix.bundle }}
          ARCH: SIM_arm64
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: List output directory
        run: ls -lah out/
      - name: Merge our tvOS libaries into XC Framework 
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: scripts/tvos/xcframework_all.sh
        env:
          BUNDLE: ${{ matrix.bundle }}
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Package
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: scripts/package.sh
        env:
          BUNDLE: ${{ matrix.bundle }}
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Update Release tvOS arm64
        if: github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release }}
          release: ${{ env.release }}
          prerelease: ${{ env.prerelease }}
          files: out/openFrameworksLibs_${{ env.release }}_${{ env.TARGET }}_${{ matrix.bundle }}.tar.bz2
