name: build-msys2

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-msys2:
    
    strategy:
      matrix:
          include: [
            { msystem: MINGW32 },
            { msystem: MINGW64 },
            { msystem: UCRT64 },
            { msystem: CLANG32 },
            { msystem: CLANG64 }
          ]
    name: ${{ matrix.msystem }}
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: ${{ matrix.msystem }}
          install: >-
            base-devel
            unzip
            dos2unix
            gperf
            git
            libxml2
            python3
      - name: Install additional msys2 packages
        run: |
          pacman -S --noconfirm ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-cmake
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: scripts/build.sh
        env:
          BUNDLE: ${{ matrix.bundle }}
          TARGET: "msys2"
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
      - name: Update Release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: nightly
          release: nightly
          prerelease: false
          files: out/openFrameworksLibs_master_msys2_mingw64.zip
        if: github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && github.ref == 'refs/heads/master'

